### ISSUE TITLE
Ubuntu does not bind to ip adress - only localhost

### ISSUE THREAD

**Issue by s1232** [marcodpt/minirps#11]
Thanks for your efforts here!

This is probably more of a question than an actual issue: I tried running minirps on my Ubuntu box. It is accessible over http://localhost but not over host ip. Other services running on the same host does not have this issue. Any hints?

**Comment by marcodpt** [comment]
Normally when it works on localhost but not via IP it may be related to the firewall.

This is very common for me on AWS and other providers.

Normally what I do is:
 - Check the firewall of the machine in question.
 - Check the router or, in the case of AWS, the access rules.

It is important at each stage to try to create the simplest examples you can to isolate the problem in question.

**Comment by marcodpt** [comment]
In the case of Ubuntu Box I never messed with it.

I believe it is a virtual machine.

I don't know how to use any operating system other than Linux.

You have to see how the host OS communicates with the Ubuntu box.

**Comment by marcodpt** [comment]
My suggestion is to use well-established commands like:

`python3 -m http.server`

which only serves static directories and is available on all Linux.

If it fails, it is certain that the problem is the Ubuntu firewall or the host OS.

Otherwise, the problem is very likely to be the `minirps`.
